[versions]
detektVersion = "1.23.1"
junitVersion = "5.10.3"
ktlintVersion = "11.6.1"
log4jVersion = "2.25.1"

[libraries]
commons-io = "commons-io:commons-io:2.20.0"
auto-service-annotations = "com.google.auto.service:auto-service-annotations:1.1.1"
auto-service-ksp = "dev.zacsweers.autoservice:auto-service-ksp:1.2.0"
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitVersion" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitVersion" }
truth = "com.google.truth:truth:1.4.4"
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:4.1.0"
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4jVersion" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4jVersion" }
jimfs = "com.google.jimfs:jimfs:1.3.0"

[plugins]
ksp = "com.google.devtools.ksp: 1.8.22-1.0.11"
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintVersion" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektVersion" }
